"""add scraper summary html images ingest columns

Revision ID: 421849edfb6d
Revises: ea503d216924
Create Date: 2026-05-20 08:13:40.484201+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '421849edfb6d'
down_revision: Union[str, None] = 'ea503d216924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_jobs', sa.Column('result_summary', sa.Text(), nullable=True))
    op.add_column('scrape_jobs', sa.Column('result_html', sa.Text(), nullable=True))
    op.add_column('scrape_jobs', sa.Column('result_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scrape_jobs', sa.Column('is_ingested', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('scrape_jobs', sa.Column('ingest_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_jobs', 'ingest_count')
    op.drop_column('scrape_jobs', 'is_ingested')
    op.drop_column('scrape_jobs', 'result_images')
    op.drop_column('scrape_jobs', 'result_html')
    op.drop_column('scrape_jobs', 'result_summary')
    # ### end Alembic commands ###
