"""add_crawl_jobs_and_crawled_pages_tables

Revision ID: 8a669e312516
Revises: 421849edfb6d
Create Date: 2026-05-20 08:22:51.081636+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a669e312516'
down_revision: Union[str, None] = '421849edfb6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('path_filter', sa.String(length=500), nullable=True),
    sa.Column('limit_pages', sa.Integer(), nullable=False),
    sa.Column('delay_seconds', sa.Float(), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawled_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawled_pages')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
